name       : gcompris
version    : '15.10'
release    : 2
source     :
    - http://gcompris.net/download/gtk/src/gcompris-15.10.tar.bz2 : 6aba73e2a1db0f50d43a40ee1a4a2b9d62a96e68542971b555c9debd8f50fc38
license    : GPL-3.0
component  : games.learning
summary    : Educational software suite comprising of numerous activities for children aged 2 to 10
description: |
    Educational software suite comprising of numerous activities for children aged 2 to 10
builddeps  :
    - pkgconfig(librsvg-2.0)
    - pkgconfig(pycairo)
    - pkgconfig(pygtk-2.0)
    - pkgconfig(SDL_mixer)
    - pkgconfig(sqlite3)
    - intltool
    - texinfo
    - texi2html
setup      : |
    %configure --enable-sdlmixer
build      : |
    %make
install    : |
    %make_install
