name       : gcompris
version    : '0.70'
release    : 3
source     :
    - git|https://anongit.kde.org/gcompris.git : V0.70
license    : GPL-3.0
component  : games.learning
summary    : Educational software suite comprising of numerous activities for children aged 2 to 10
description: |
    Educational software suite comprising of numerous activities for children aged 2 to 10
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5QuickWidgets)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
setup      : |
    mkdir build
    pushd build
    %cmake ..
    popd
build      : |
    pushd build
    %make
    popd
install    : |
    pushd build
    %make_install
    popd
    install -Dm00644 org.kde.gcompris.appdata.xml $installdir/usr/share/appdata/org.kde.gcompris.appdata.xml
    install -Dm00644 GCompris64.png $installdir/usr/share/pixmaps/gcompris-qt.png
    install -Dm00644 org.kde.gcompris.desktop $installdir/usr/share/applications/org.kde.gcompris.desktop
