name       : gcompris
version    : '0.90'
release    : 8
source     :
    - http://gcompris.net/download/qt/src/gcompris-qt-0.90.tar.xz : eaab8805ae8c1e4fa04ba6cdfe437fca6082f2d9848dc83b4e04bd086d6faac4
license    : GPL-3.0
component  : games
summary    : Educational software suite comprising of numerous activities for children aged 2 to 10
description: |
    GCompris is a high quality educational software suite, including a large number of activities for children aged 2 to 10.
    Some of the activities are game orientated, but nonetheless still educational.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5QuickWidgets)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - qml-box2d
rundeps    :
    - qml-box2d
    - qt5-graphicaleffects
    - qt5-multimedia
    - qt5-quickcontrols
    - qt5-svg
setup      : |
    mkdir build && pushd build
    %cmake -DQML_BOX2D_LIBRARY=%libdir%/qt5/qml/Box2D.2.0 \
        ..
build      : |
    %make -C build
install    : |
    %make_install -C build
