name       : gcompris
version    : 0.97
release    : 12
source     :
    - https://gcompris.net/download/qt/src/gcompris-qt-0.97.tar.xz : 871c6749def44284d0920d11480728db7983a81b348f7e275ef6662b65508342
license    : GPL-3.0-or-later
component  : games
summary    : Educational software suite comprising of numerous activities for children aged 2 to 10
description: |
    GCompris is a high quality educational software suite, including a large number of activities for children aged 2 to 10.
    Some of the activities are game orientated, but nonetheless still educational.
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5QuickWidgets)
    - pkgconfig(Qt5Sensors)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
    - kdoctools-devel
    - qml-box2d
rundeps    :
    - qml-box2d
    - qt5-graphicaleffects
    - qt5-multimedia
    - qt5-quickcontrols
    - qt5-svg
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
